apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: behemoth-md-upload
spec:
  schedule: "@midnight"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: behemoth-md-upload
            image: cloudwallcapital/serenity:2020.04.26-b13
            command: ["python"]
            args: ["serenity/fh/behemoth_upload.py"]
            env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database-secret-config
                  key: password
            volumeMounts:
            - mountPath: /behemoth
              name: behemoth
          restartPolicy: OnFailure
          volumes:
            - name: behemoth
              persistentVolumeClaim:
                claimName: behemoth-pv-claim
