kind: PersistentVolume
apiVersion: v1
metadata:
  name: behemoth-pv-volume
  labels:
    type: local
    app: behemoth
spec:
  storageClassName: manual
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/raid/data/behemoth"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: behemoth-pv-claim
  labels:
    app: behemoth
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
