apiVersion: apps/v1
kind: Deployment
metadata:
  name: coinbasepro-fh
  labels:
    app: coinbasepro-fh
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coinbasepro-fh
  template:
    metadata:
      labels:
        app: coinbasepro-fh
    spec:
      containers:
        - name: phemex-fh
          image: cloudwallcapital/serenity:2020.04.26-b13
          command: ["python"]
          args: ["serenity/fh/coinbasepro_fh.py"]
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database-secret-config
                  key: password
          volumeMounts:
            - mountPath: /behemoth
              name: behemoth 
      volumes:
        - name: behemoth
          persistentVolumeClaim:
            claimName: behemoth-pv-claim
