apiVersion: v1
kind: Service
metadata:
  name: serenity-jupyterlab-nodeport
  labels:
    app: serenity-jupyterlab
spec:
  type: NodePort
  ports:
  - port: 8888
    nodePort: 30888
  selector:
    app: serenity-jupyterlab
